#!/bin/bash
# ---------------------------------------------------------------
# chkconfig: 2345 80 20
# description: Startup/shutdown script for nVidia CUDA Toolkit.
# ---------------------------------------------------------------
### BEGIN INIT INFO
# Provides: nvidia-cuda-toolkit
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop: 0 1 2 6
# Short-Description: Startup/shutdown script for nVidia CUDA Toolkit.
# Description: Startup/shutdown script for nVidia CUDA Toolkit.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DRIVER=nvidia
RETVAL=0

# Create /dev nodes for nvidia devices
function createnodes() {
   # Count the number of NVIDIA controllers found.
   N3D=`/sbin/lspci | grep -i NVIDIA | grep "3D controller" | wc -l`
   NVGA=`/sbin/lspci | grep -i NVIDIA | grep "VGA compatible controller" | wc -l`

   N=`expr $N3D + $NVGA - 1`
   for i in `seq 0 $N`; do
       mknod -m 666 /dev/nvidia$i c 195 $i || :
       RETVAL=$?
       [ "$RETVAL" = 0 ] || exit $RETVAL || :
   done

   mknod -m 666 /dev/nvidiactl c 195 255
   RETVAL=$?
   [ "$RETVAL" = 0 ] || exit $RETVAL
}

# Remove /dev nodes for nvidia devices
function removenodes() {
   rm -f /dev/nvidia*
}

# Start daemon
function start() {
   echo -n $"Loading $DRIVER kernel module: "
   modprobe $DRIVER && success || failure
   RETVAL=$?
   echo
   [ "$RETVAL" = 0 ] || exit $RETVAL

   echo -n $"Initializing CUDA /dev entries: "
   createnodes && success || failure
   RETVAL=$?
   echo
   [ "$RETVAL" = 0 ] && touch /var/lock/subsys/nvidia-cuda-toolkit || exit $RETVAL
}

# Stop daemon
function stop() {
   echo -n $"Unloading $DRIVER kernel module: "
   rmmod -f $DRIVER && success || failure
   RETVAL=$?
   echo
   [ "$RETVAL" = 0 ] || exit $RETVAL

   echo -n $"Removing CUDA /dev entries: "
   removenodes && success || failure
   RETVAL=$?
   echo
   [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/nvidia-cuda-toolkit || exit $RETVAL
}

function status() {
   # Count the number of NVIDIA controllers found.
   N3D=`/sbin/lspci | grep -i NVIDIA | grep "3D controller" | wc -l`
   NVGA=`/sbin/lspci | grep -i NVIDIA | grep "VGA compatible controller" | wc -l`

   N=`expr $N3D + $NVGA - 1`
   for i in `seq 0 $N`; do
       [ -b /dev/nvidia$i ] || { echo "/dev/nvidia$i device node missing, restart the service."; return 3; }
   done

   [ -b /dev/nvidiactl ] || { echo "/dev/nvidiactl device node missing, restart the service."; return 3; }

   if ! lsmod | grep $DRIVER >& /dev/null; then
       echo "$DRIVER module not loaded, restart the service."
       return 3;
   fi
}

# See how we were called
case "$1" in
   start)
       start
      ;;
   stop)
       status >& /dev/null && stop
      ;;
   restart)
       stop
       start
      ;;
   reload|force-reload)
       stop
	   start
	  ;;
   status)
       status
	  ;;
   condrestart|try-restart)
       status >& /dev/null || exit 0
	   stop
	   start
	  ;;
   *)
      echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
      RETVAL=2
esac
exit $RETVAL
