#!/bin/bash 

if ! grep -q net.ipv4.ip_forward=1 /etc/sysctl.conf ; then
echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf

fi 

sysctl -w net.ipv4.ip_forward=1 
/sbin/iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

if ! grep -q MASQUERADE /etc/rc.local ; then

echo "#####
iptables -X
iptables -F
iptables -t nat -X
iptables -t nat -F
iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD  -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t nat -I POSTROUTING -o eth1 -j MASQUERADE 
" >> /etc/rc.local
fi

chmod +x /etc/rc.d/rc.local 

